# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

# Варіант 1: з використанням стандартних методів python, наприклад 'range', але всі ці методи працюють повільніше за методи бібліотеки numpy
v = np.array(range(1,11))
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# варіант 2: за допомогою функції 'arange'. Особливість - дозволяє встановити крок, в т.ч. не кратний 1:
v1 = np.arange(1,11, 1)
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# варіант 3: за допомогою функції 'linspace' (дозволяє встановите стартове та кінцеве значення, а також кількіть даних який необхідний в цьому проміжку):
v_1 = np.linspace(1,10, num=10, dtype=int)
v_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [ ]:
# варіант 1: за допомогою функції 'zeros'
v2 = np.zeros((3,3), dtype=int)
v2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# варіант 2: за допомогою функції 'full' (дозволяє заповнити масив будь-яким значенням, в даному випадку нулем)
v_2 = np.full((3,3), 0)
v_2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
v_3 = np.random.randint(1, 11, size=(5,5))
v_3

array([[ 6,  2,  9,  9,  2],
       [ 3,  5,  1,  5,  2],
       [ 6, 10,  3,  7,  2],
       [ 5,  8,  1,  5,  9],
       [ 5,  7,  4,  1,  5]])

In [ ]:
# або для перетворень ще може знадобитися функція 'reshape':
v_31 = np.random.randint(1, 11, 25).reshape(5,5)
v_31

array([[ 4,  3,  9,  9,  4],
       [ 3, 10,  6,  8,  7],
       [10,  2, 10, 10,  4],
       [ 7,  4,  1,  8,  6],
       [ 8,  2,  1,  3,  3]])

# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
v_4 = np.random.random((4, 4))
v_4

array([[0.64426609, 0.94691817, 0.08134969, 0.57996501],
       [0.60482938, 0.06037345, 0.76049253, 0.16311622],
       [0.73200079, 0.59715268, 0.59961175, 0.26774493],
       [0.32825376, 0.30482343, 0.64505047, 0.41548927]])

# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
v5 = np.random.randint((1,11), size=(5,1))
w5 = np.random.randint((1,11), size=(5,1))


In [ ]:
v5

array([[0],
       [6],
       [0],
       [0],
       [0]])

In [ ]:
w5

array([[0],
       [6],
       [0],
       [7],
       [0]])

In [ ]:
# Додавання двох масивів. Варіант 1:
sum = v5 + w5
sum

array([[ 0],
       [12],
       [ 0],
       [ 7],
       [ 0]])

In [ ]:
# Додавання двох масивів. Варіант 2: за допомогою функції 'add'
sum_1 = np.add(v5,w5)
sum_1

array([[ 0],
       [12],
       [ 0],
       [ 7],
       [ 0]])

In [ ]:
# Віднімання двох масивів. Варіант 1:
sub_1 = v5 - w5
sub_1

array([[ 0],
       [ 0],
       [ 0],
       [-7],
       [ 0]])

In [ ]:
# Віднімання двох масивів. Варіант 2: за допомогою функції 'subtract'
sub_2 = np.subtract(v5, w5)
sub_2

array([[ 0],
       [ 0],
       [ 0],
       [-7],
       [ 0]])

In [ ]:
# Множення двох масивів. Варіант 1:
multy_1 = v5 * w5
multy_1

array([[ 0],
       [36],
       [ 0],
       [ 0],
       [ 0]])

In [ ]:
# Множення двох масивів. Варіант 2: за допомогою функції 'multiply':
multy_2 = np.multiply(v5, w5)
multy_2

array([[ 0],
       [36],
       [ 0],
       [ 0],
       [ 0]])

# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
v_6 = np.random.randint(1, 10, size=(7,))
w_6 = np.random.randint(1, 100, size=(7,))

In [ ]:
v_6

array([1, 7, 3, 9, 3, 8, 7])

In [ ]:
w_6

array([92, 91, 39, 75, 38,  7, 82])

In [ ]:
result_6 = np.dot(v_6, w_6)
result_6

2265

# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [3]:
v_7 = np.random.randint(1, 11, size=(2, 2))
w_7 = np.random.randint(1, 11, size=(2, 3))
v_7

array([[5, 7],
       [5, 4]])

In [4]:
w_7

array([[ 1,  4,  2],
       [10,  8, 10]])

In [9]:
# Варіант 1: за допомогою функції 'dot':
result_7 = np.dot(v_7, w_7)
result_7

array([[75, 76, 80],
       [45, 52, 50]])

In [8]:
# Варіант 2: за допомогою функції 'matmul':
result_71 = np.matmul(v_7, w_7)
result_71

array([[75, 76, 80],
       [45, 52, 50]])

In [10]:
# Варіант 3: за допомогою '@'
v_7@w_7

array([[75, 76, 80],
       [45, 52, 50]])

# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
v_8 = np.random.randint(1, 10, size=(3,3))
v_8

array([[7, 3, 8],
       [7, 4, 3],
       [7, 8, 2]])

In [ ]:
result_8 = np.linalg.inv(v_8)
result_8

array([[-0.12030075,  0.43609023, -0.17293233],
       [ 0.05263158, -0.31578947,  0.26315789],
       [ 0.21052632, -0.26315789,  0.05263158]])

# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
v_9 = np.random.random((4,4))
v_9

array([[0.37162421, 0.42763823, 0.58861793, 0.91731653],
       [0.11794932, 0.31130514, 0.70987407, 0.69560032],
       [0.93279983, 0.79763395, 0.6680822 , 0.30388822],
       [0.17496526, 0.83307637, 0.99978418, 0.08572214]])

In [ ]:
# варіант 1:
result_9 = v_9.T
result_9

array([[0.37162421, 0.11794932, 0.93279983, 0.17496526],
       [0.42763823, 0.31130514, 0.79763395, 0.83307637],
       [0.58861793, 0.70987407, 0.6680822 , 0.99978418],
       [0.91731653, 0.69560032, 0.30388822, 0.08572214]])

In [ ]:
# варіант 2: за допомогою функції 'transpose'
result_91 = np.transpose(v_9)
result_91

array([[0.37162421, 0.11794932, 0.93279983, 0.17496526],
       [0.42763823, 0.31130514, 0.79763395, 0.83307637],
       [0.58861793, 0.70987407, 0.6680822 , 0.99978418],
       [0.91731653, 0.69560032, 0.30388822, 0.08572214]])

# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
v_10 = np.random.randint(1,11, size=(3, 4))
w_10 = np.random.randint(1,11, size=(4,))

In [ ]:
v_10


array([[ 9,  1,  8,  6],
       [ 1,  3,  4,  3],
       [ 8,  5, 10,  8]])

In [ ]:
w_10


array([1, 5, 8, 7])

In [ ]:
result_10 = np.dot(v_10, w_10)
result_10

array([120,  69, 169])

# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
v_11 = np.random.random((2,3))
w_11 = np.random.random((3))
v_11

array([[0.98746967, 0.68979218, 0.96445067],
       [0.40830701, 0.89897612, 0.30179568]])

In [ ]:
w_11

array([0.65837996, 0.48105061, 0.25755001])

In [ ]:
result_11 = np.dot(v_11, w_11)
result_11

array([1.23034946, 0.77900164])

# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
v_12 = np.random.randint(1,10, (2,2))
w_12 = np.random.randint(1,10, (2,2))
print(v_12)
print()
print(w_12)
print()
result_12 = np.multiply(v_12, w_12)
result_12

[[6 5]
 [5 8]]

[[6 4]
 [7 5]]



array([[36, 20],
       [35, 40]])

# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
v_13 = np.random.randint(1,10, (2,2))
w_13 = np.random.randint(1,10, (2,2))
print(v_13)
print()
print(w_13)
print()
result_13 = np.dot(v_13, w_13)
result_13

[[1 1]
 [1 3]]

[[6 9]
 [1 2]]



array([[ 7, 11],
       [ 9, 15]])

# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
v_14 = np.random.randint(1,101, (5,5))
print(v_14)
print()
result_14 = np.sum(v_14)
print(result_14)
print()
# або:
print(result_14.sum())

[[  3  15  93  81  48]
 [ 45  31  73  67  37]
 [ 55   8  22   4  65]
 [ 62   7  61  36  11]
 [ 81  78 100  84  74]]

1241

1241


# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.



In [ ]:
v_15 = np.random.randint(1,11, (4,4))
w_15 = np.random.randint(1,11, (4,4))
print(v_15)
print()
print(w_15)
print()
result_15 = v_15 - w_15
result_15

[[ 3  9  6  9]
 [ 6  8  6  2]
 [ 4 10  8  9]
 [ 8  5 10  9]]

[[10  3  5  3]
 [ 4  5  2  7]
 [ 1  1  6  5]
 [ 7  4  5  6]]



array([[-7,  6,  1,  6],
       [ 2,  3,  4, -5],
       [ 3,  9,  2,  4],
       [ 1,  1,  5,  3]])

# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
v_16 = np.random.random((3,3))
w_16 = np.zeros((3,1))
print(v_16)
print()
print(w_16)
print()
w_16[0] = np.sum(v_16[0])
w_16[1] = np.sum(v_16[1])
w_16[2] = np.sum(v_16[2])
print(w_16)
print()

# варіант 2: в функції 'sum' вказуємо по якій осі необхідно рахувати суму. Потім перетворюємо вектор на матрицю-стовбець за допомогою 'reshape'
print(v_16.sum(axis=1).reshape(-1,1))  # в функції 'reshape' першим значенням передали "-1", тобто numpy кількість рядків визначить автоматично

[[0.06224484 0.86169918 0.77343623]
 [0.89996322 0.32557788 0.93387979]
 [0.8344806  0.35653432 0.77704492]]

[[0.]
 [0.]
 [0.]]

[[1.69738025]
 [2.15942089]
 [1.96805985]]

[[1.69738025]
 [2.15942089]
 [1.96805985]]


# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [ ]:
v_17 = np.random.randint(1,100, (3,4))
print(v_17)
print()
result_17 = v_17 ** 2
result_17

[[83 91 51 20]
 [71 65 85 24]
 [58 98 76 40]]



array([[6889, 8281, 2601,  400],
       [5041, 4225, 7225,  576],
       [3364, 9604, 5776, 1600]])

# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
v_18 = np.random.randint(1,51, (4,))
print(v_18)
print()
result_18 = np.sqrt(v_18)
result_18

[38 10  7 33]



array([6.164414  , 3.16227766, 2.64575131, 5.74456265])